package fsd.msservice.product.api.model;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class SuggestCarouselVO implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 1204789156359391956L;

	/** carousel id generated by database */
	private Integer id;

	/** product id binding to this carousel image */
	private String productId;

	/** image url */
	private String imageUrl;

	/** title */
	private String title;

	/** description */
	private String description;

	private Date start;

	private Date end;
}
