package fsd.model.product;

import java.math.BigDecimal;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class ProductSummaryVO {

	/**
	 * product id which is generated by database
	 */
	private String id;

	/**
	 * manufacture id
	 */
	private String manufacture;

	/**
	 * seller id
	 */
	private String sellerId;

	private String sellerName;

	/**
	 * product price
	 */
	private BigDecimal price;

	/**
	 * product tax
	 */
	private BigDecimal tax;

	/**
	 * product name
	 */
	private String name;

	private String imageUrl;

	/**
	 * product enable flag
	 * <ul>
	 * <li>0: Normal
	 * <li>1: product is locked
	 * <li>2: product is disabled
	 * </ul>
	 */
	private String status;

}