package fsd.model.product;

import java.math.BigDecimal;
import java.util.List;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class ProductDetailVO {

	/**
	 * product id which is generated by database
	 */
	private String id;

	/**
	 * category id
	 */
	private String categoryId;

	private String categoryName;

	/**
	 * subcatetory id
	 */
	private String subcategoryId;

	/**
	 * subcatetory Name
	 */
	private String subcategoryName;

	/**
	 * seller id
	 */
	private String sellerId;

	private String sellerName;

	/**
	 * product price
	 */
	private BigDecimal price;

	/**
	 * product tax
	 */
	private BigDecimal tax;

	/**
	 * product name
	 */
	private String name;

	/**
	 * description
	 * </p>
	 */
	private String description;

	/**
	 * Stock number
	 */
	private Integer stockNumber;

	/**
	 * Remark
	 */
	private String remarks;

	private String imageUrl;

	private List<ProductCarouselVO> carouses;

	/**
	 * product enable flag
	 * <ul>
	 * <li>0: Normal
	 * <li>1: product is locked
	 * <li>2: product is disabled
	 * </ul>
	 */
	private String status;

}