package fsd.common.model.product;

import java.io.Serializable;
import java.math.BigDecimal;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class ProductSummaryVO implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -7411085977965135825L;

	/**
	 * product id which is generated by database
	 */
	private String id;

	/**
	 * product name
	 */
	private String name;

	/** product image url */
	private String imageUrl;

	/**
	 * manufacture
	 */
	private String manufacture;

	/**
	 * seller id
	 */
	private String sellerId;

	/** seller name */
	private String sellerName;

	/**
	 * product price
	 */
	private BigDecimal price;

	/**
	 * product tax
	 */
	private BigDecimal tax;

}