
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emart?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/