spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/emart?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/