server:
    port: 2100

spring:
    application:
        name: fsd-auth
    datasource:
        driver-class-name: com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/emart?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        username: emartuser
        password: 1234
    jpa:
        generate-ddl: true
        show-sql: true
        properties:
            hibernate: 
                format-sql: true
        hibernate:
            #ddl-auto: none
            ddl-auto: update

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true