app.auth-path-config:
  #allow access for rest api who login / get token
  login-path:
    - url:
        - /auth/login

server:
  port: 2105

spring:
  application:
    name: fsd-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emart?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: emartuser
    password: 1234
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 1
      max-idle: 5
      min-idle: 2
      max-wait-millis: 10000
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate: 
        format-sql: true
    hibernate:
      #ddl-auto: none
      ddl-auto: update

logging:
  level:
    org.hibernate.type: TRACE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true